name: Test Action

on:
  push:
    branches:    
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
    
    - uses: actions/checkout@main
    - name: 'Test'
      uses: ./
      with:
        id: 'SMCaetano.Pdv.Core'
        username: ${{secrets.NUGET_USUARIO}}
        password: ${{secrets.NUGET_PAT}}
